# Generated by Django 4.2.11 on 2024-03-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_amarillo', models.IntegerField(max_length=100, verbose_name='Promedio de Tarjetas Amarillas')),
            ],
        ),
        migrations.CreateModel(
            name='preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arbitro', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.arbitro', verbose_name='Arbitro')),
            ],
        ),
        migrations.CreateModel(
            name='calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(max_length=100, verbose_name='Hora')),
                ('partido', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.partido', verbose_name='Hora')),
            ],
        ),
    ]
