# Generated by Django 4.2.11 on 2024-03-30 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitro',
            name='nombre',
            field=models.CharField(default='Nombre por defecto', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AddField(
            model_name='arbitro',
            name='promedio_rojo',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=5, verbose_name='Promedio de Tarjetas Rojas'),
        ),
        migrations.AddField(
            model_name='calendario',
            name='fecha',
            field=models.TextField(default='00/00/00', max_length=100, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='calendario',
            name='lugar',
            field=models.CharField(default='Lugar', max_length=100, verbose_name='Lugar'),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_local',
            field=models.CharField(default='Nombre por defecto', max_length=100, verbose_name='Equipo Local'),
        ),
        migrations.AddField(
            model_name='partido',
            name='equipo_visitante',
            field=models.CharField(default='Nombre por defecto', max_length=100, verbose_name='Equipo Visitante'),
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado',
            field=models.CharField(default='0-0', max_length=100, verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='preguntas',
            field=models.TextField(default='Pregunta por defecto', max_length=200, verbose_name='Preguntas'),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='respuesta',
            field=models.TextField(default='Respuesta por defecto', max_length=200, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='arbitro',
            name='promedio_amarillo',
            field=models.DecimalField(decimal_places=2, default='0.0', max_digits=5, verbose_name='Promedio de Tarjetas Amarillas'),
        ),
        migrations.AlterField(
            model_name='calendario',
            name='hora',
            field=models.TimeField(default='00:00', max_length=100, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='autor',
            field=models.CharField(default='Nombre por defecto', max_length=100, verbose_name='Autor'),
        ),
    ]
