# Generated by Django 4.2.11 on 2024-03-31 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_arbitro_nombre_arbitro_promedio_rojo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntas',
            name='respuesta',
        ),
    ]
