# Generated by Django 4.2.11 on 2024-03-31 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_preguntas_respuesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(default='Respuesta por defecto', max_length=200, verbose_name='Respuesta')),
                ('pregunta', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.preguntas', verbose_name='Preguntas')),
            ],
        ),
    ]
