# Generated by Django 4.2.11 on 2024-04-01 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partido',
            name='resultado',
        ),
        migrations.CreateModel(
            name='resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(default='0-0', max_length=100, verbose_name='Resultado')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.partido', verbose_name='Partido')),
            ],
        ),
    ]
