# Generated by Django 4.2.11 on 2024-04-01 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_remove_partido_resultado_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='fecha',
            field=models.DateField(default='00/00/00', max_length=100, verbose_name='Fecha'),
        ),
    ]
